site_name: Портфолио лабораторных работ
theme:
  name: material

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная 1: labs/lab1.md
      - Лабораторная 2: labs/lab2.md
      - Лабораторная 3: labs/lab3.md